/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.26
 * Generated at: 2016-04-12 06:52:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.Dbconnection.Dbconnection;

public final class company_0020papers_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
try
{
  String uid=request.getParameter("uid1");
session.setAttribute("uid1",uid);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<Script Language=\"JavaScript\">\r\n");
      out.write("function xyz()\r\n");
      out.write("{\r\n");
      out.write("  window.open(\"timer.jsp?v=0\",\"exampaper\",\"width=1024,height=768,toolbar=false,status=false,menubar=false,directories=false,resizable=false\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</Script><title></title>\r\n");
      out.write("<link rel=stylesheet href=st.css type=text/css>\r\n");
      out.write("<LINK \r\n");
      out.write("media=screen,projection,print \r\n");
      out.write("href=\"dropdown/main.css\" type=text/css \r\n");
      out.write("rel=stylesheet>\r\n");
      out.write("<!-- UDM 4 -->\r\n");
      out.write("<SCRIPT src=\"dropdown/udm_custom.js\" \r\n");
      out.write("type=text/javascript></SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT src=\"dropdown/udm_control.js\" \r\n");
      out.write("type=text/javascript></SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT src=\"dropdown/udm_style.js\" \r\n");
      out.write("type=text/javascript></SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT src=\"dropdown/udm_slide.js\" \r\n");
      out.write("type=text/javascript></SCRIPT>\r\n");
      out.write("\r\n");
      out.write("<SCRIPT src=\"dropdown/dropdown.js\" \r\n");
      out.write("type=text/javascript></SCRIPT>\r\n");
      out.write("</head>\r\n");
      out.write("<BODY >\r\n");
      out.write("<input type=text value=");
      out.print(uid);
      out.write(" size=\"20\" >\r\n");
      out.write("<table  valign=\"top\" cellpadding=0 cellspacing=0 width=\"800\"  align=center  bordercolor=\"#2A8DCC\" >\r\n");
      out.write(" <tr><td valign=top class=to width=\"800\" bgcolor=\"0F4F8D\">\r\n");
      out.write("<table width=\"800\" cellpadding=0 cellspacing=0 height=\"144\" >\r\n");
      out.write(" <tr><td width=\"800\" height=\"144\"><IMG id=IMG1 height=144 src=\"img/sri1.gif\" width=\"100%\" ></td></tr>\r\n");
      out.write("<tr><td width=\"800\" height=\"10\"><IMG height=40 src=\"img/m021.gif\" width=326 ></td></tr></table></tr>\r\n");
      out.write("\r\n");
      out.write("  <table width=\"800\" border=\"1\"  bordercolor=\"#2A8DCC\">\r\n");
      out.write("<tr><td valign=left width=\"200\" class=ma colspan=2>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table cellSpacing=0 cellPadding=0 width=\"100%\" border=0>\r\n");
      out.write("<tr><td vAlign=center align=middle colSpan=2>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr><td height=15></td></tr>\r\n");
      out.write("<TR><TD vAlign=center align=middle ><IMG height=1 src=\"img/D2_Blueline.gif\" width=\"98%\"></TD></TR>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center height=22><IMG height=5\r\n");
      out.write("                              src=\"img/D4_redbullet.gif\" \r\n");
      out.write("                             width=5> \r\n");
      out.write("                            <FONT height=10\r\n");
      out.write("                              face=\"Verdana, Arial, Helvetica, sans-serif\" \r\n");
      out.write("                              color=#ffffff size=2>\r\n");
      out.write("                             <A class=links href=\"changepassword.jsp?v=0\">Change Password</A></FONT></TD></TR>\r\n");
      out.write("\r\n");
      out.write("<TR> <TD vAlign=center align=middle colSpan=2>\r\n");
      out.write("<IMG height=1 src=\"img/D2_Blueline.gif\" width=\"98%\"></TD></TR>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center height=22><IMG height=5\r\n");
      out.write("                              src=\"img/D4_redbullet.gif\" \r\n");
      out.write("                             width=5> \r\n");
      out.write("                            <FONT \r\n");
      out.write("                              face=\"Verdana, Arial, Helvetica, sans-serif\" \r\n");
      out.write("                              color=#ffffff size=2>\r\n");
      out.write("                             <a class=links href=\"recruitment.jsp?v=0\">Recruitment Procedures</FONT></TD></TR>\r\n");
      out.write("\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center align=middle colSpan=2><IMG \r\n");
      out.write("                              height=1\r\n");
      out.write("                              src=\"img/D2_Blueline.gif\" \r\n");
      out.write("                              width=\"98%\"></TD></TR>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center height=22><IMG height=5\r\n");
      out.write("                              src=\"img/D4_redbullet.gif\" \r\n");
      out.write("                             width=5> \r\n");
      out.write("                            <FONT \r\n");
      out.write("                              face=\"Verdana, Arial, Helvetica, sans-serif\" \r\n");
      out.write("                              color=#ffffff size=2>\r\n");
      out.write("                             <a class=links href=\"companypapers.jsp?v=0\">Previous Papers</FONT></TD></TR>\r\n");
      out.write("\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center align=middle colSpan=2><IMG \r\n");
      out.write("                              height=1\r\n");
      out.write("                              src=\"img/D2_Blueline.gif\" \r\n");
      out.write("                              width=\"98%\"></TD></TR>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center height=22><IMG height=5\r\n");
      out.write("                              src=\"img/D4_redbullet.gif\" \r\n");
      out.write("                             width=5> \r\n");
      out.write("                            <FONT \r\n");
      out.write("                              face=\"Verdana, Arial, Helvetica, sans-serif\" \r\n");
      out.write("                              color=#ffffff size=2>\r\n");
      out.write("                             <a class=links href=\"schedule.jsp?v=0\">Exam Schedule</FONT></TD></TR>\r\n");
      out.write("\r\n");
      out.write("<TR><TD vAlign=center align=middle colSpan=2>\r\n");
      out.write("<IMG height=1 src=\"img/D2_Blueline.gif\" width=\"98%\"></TD></TR>\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center height=22><IMG height=5\r\n");
      out.write("                              src=\"img/D4_redbullet.gif\" \r\n");
      out.write("                             width=5> \r\n");
      out.write("                            <FONT \r\n");
      out.write("                              face=\"Verdana, Arial, Helvetica, sans-serif\" \r\n");
      out.write("                              color=#ffffff size=2>\r\n");
      out.write("                             <a class=links href=\"recruitment.jsp?uid1=");
      out.print(uid);
      out.write("\" onclick=\"xyz()\" >Exam Paper</FONT></TD></TR>\r\n");
      out.write("\t\t\t\t\t\t\t \r\n");
      out.write("<TR> <TD vAlign=center align=middle colSpan=2>\r\n");
      out.write("<IMG height=1 src=\"img/D2_Blueline.gif\" width=\"98%\"></TD></TR>\r\n");
      out.write("\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center height=22><IMG height=5\r\n");
      out.write("                              src=\"img/D4_redbullet.gif\" \r\n");
      out.write("                             width=5> \r\n");
      out.write("                            <FONT \r\n");
      out.write("                              face=\"Verdana, Arial, Helvetica, sans-serif\" \r\n");
      out.write("                              color=#ffffff size=2>\r\n");
      out.write("                             <a class=links href=\"results.jsp?v=0\">Result</FONT></TD></TR>\r\n");
      out.write("<TR> <TD vAlign=center align=middle colSpan=2>\r\n");
      out.write("<IMG height=1 src=\"img/D2_Blueline.gif\" width=\"98%\"></TD></TR>\r\n");
      out.write("\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center height=22><IMG height=5\r\n");
      out.write("                              src=\"img/D4_redbullet.gif\" \r\n");
      out.write("                             width=5> \r\n");
      out.write("                            <FONT \r\n");
      out.write("                              face=\"Verdana, Arial, Helvetica, sans-serif\" \r\n");
      out.write("                              color=#ffffff size=2>\r\n");
      out.write("                             <a class=links href=\"logout.jsp?v=0\">Logout</FONT></TD></TR>\r\n");
      out.write("<TR> <TD vAlign=center align=middle colSpan=2>\r\n");
      out.write("<IMG height=1 src=\"img/D2_Blueline.gif\" width=\"98%\"></TD></TR>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</font></table></td>\r\n");
      out.write("<td width=\"600\">\r\n");
      out.write("\r\n");
      out.write("<table width=100% height=18 class=links>\r\n");
      out.write("<tr><td height=15></td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td bgcolor=\"0077c0\" width=\"90\" align=center><a style=\"color: white\" class=link1 href=\"company papers.jsp\">Satyam</a></td>\r\n");
      out.write("<td bgcolor=\"0077c0\" width=\"80\" align=center><a style=\"color: white\" class=link1  href=\"wipro.jsp\">Wipro</a></td>\r\n");
      out.write("<td bgcolor=\"0077c0\" width=\"99\" align=center><a style=\"color: white\" class=link1  href=\"infosys.jsp\">Infosys</a></td>\r\n");
      out.write("<td bgcolor=\"0077c0\" width=\"78\" align=center><a style=\"color: white\" class=link1  href=\"ibm.jsp\">IBM</a></td>\r\n");
      out.write("<td bgcolor=\"0077c0\" width=\"150\" align=center><a style=\"color: white\" class=link1  href=\"tech.jsp\">Tech Mahendra</a></td>\r\n");
      out.write("<td bgcolor=\"0077c0\" width=\"99\" align=center><a style=\"color: white\" class=link1  href=\"cts.jsp\">Cognizant</a></td></tr></table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<table align=center width=\"90%\">\r\n");
      out.write("<tr><td><center><h4><u><font color=\"0077c0\">Sample Test Paper for Satyam</font></u><h4></center></tr></td>\r\n");
      out.write("<tr><td>1.Fathers age 3years back is twice the sons age. the sum of fathers and sons age after 10 years   from now is 66.what is fathers age? <br><br></tr></td>\r\n");
      out.write("<tr><td>2.\t1 3 3 6 5 9 7 12__ __ __ <br><br></tr></td>\r\n");
      out.write("<tr><td>3.\t3 8 27 112 __ ___ <br><br></tr></td>\r\n");
      out.write("<tr><td>4.\t There r 6 people named madhavi, pramod, pravven, asha, gopal, nisha.they r seated around the table.<br><br>\r\n");
      out.write("\r\n");
      out.write(" &nbsp;&nbsp;&nbsp;1. madhavi and pramod always are left to a women.<br><br>\r\n");
      out.write("\r\n");
      out.write("&nbsp;&nbsp;&nbsp;2. asha and gopal are always opposite to a man.<br><br>\r\n");
      out.write("\r\n");
      out.write("&nbsp;&nbsp;&nbsp;3. some conditions are given and we have to find the order in which they sit. <br><br></tr></td>\r\n");
      out.write("<tr><td>5.\tIf a man had traveled 3km/hr faster he would have reached 40 min earlier, if he would have traveled 2 km/hr slower he would have reached 40 min late. what is distance he had traveled. <br><br></tr></td>\r\n");
      out.write("<tr><td>6.\tJohn works for 60 days for the day he is present he is paid 7.00/- and for the day he is absent he is paid 3.00/- per day. if he is paid 170/-.how many days he is present. <br><br></tr></td>\r\n");
      out.write("<tr><td>7.\tThere r 4 links in a gold chain .1 has 5links,other has 4 links and the other 3 links. goldsmith takes 50.00paise to open the link and 1.00/- to attach the link. what is least cost to bake whole bracelet. <br><br>\r\n");
      out.write("<tr><td>8.\t A cyclist moves half the speed of Tonga driver and Tonga driver moves half the speed of man walking .If man walks at 3kms per hour what is the time that cyclist covers 27kms. </tr></td>\r\n");
      out.write("<tr><td>9.\tThere r 600 pages .there is 1 error on avg per page. what is the probability that there are n errors per page. <br><br></tr></td>\r\n");
      out.write("<tr><td>10.\tA square is of side 1 km.A man travels first 2 sides with the 30 mph and third side with 60 kmph.what is the speed that man has to travel the fourth side if the avg speed is 60kmph <br><br></tr></td>\r\n");
      out.write("<tr><td>11.\tA Student got 78 marks in avg of 4 subjects. the avg of 5 subjects is 80.what are the marks he got in 5th subject. <br><br></tr></td>\r\n");
      out.write("<tr><td>12.\tHow many kg of salt at 42 paisa per kg must a man mix with 25kg of salt at 24 paisa per kg so that he may, on selling the mixture at 40 paisa per kg gain 25% on the outlay? \r\n");
      out.write("<br>A)15 kg B)20 kg C)25 kg D)28 kg E)none of these <br><br></tr></td>\r\n");
      out.write("<tr><td>13.\tFind the least number which when divided by 20,25,30,36 and 48 leaves the remainders 15,20,25,31,43 respectively.\r\n");
      out.write("<br>A)3685 B)3585 C)3595 D)3535 E)None of these <br><br></tr></td>\r\n");
      out.write("<tr><td>14.\tA sheet of metal in the form of a sector of a circle of angle 90 degrees and radius 16cm is folded to form an open conical cup. The capacity of the cup is\r\n");
      out.write("<br>A)64 sqrt(15)cm3 B)64 sqrt(5/3)TTcm3 C) 64 sqrt(5)TT D) 64/3sqrt(15)cm3 E)None of these <br><br></tr></td>\r\n");
      out.write("<tr><td>15.\tA man distributes 0.375 of his money to his wife and 0.4 to his son. He has still Rs.3,375 left with him. How much did his wife get?\r\n");
      out.write("<br>A)4565 B)5625 C)4265 D)5265 E)None of these <br><br></tr></td>\r\n");
      out.write("<tr><td>16.\tThree faces of a fair die are Yellow, two faces red and one blue.The die is tossed three times. The probability that the colours, yellow,red and blue appear in the first,second and third tosses respectively is \r\n");
      out.write("<br>A)1/36 B)1/18 C)1/32 D)1/37 E)None of these <br><br></tr></td>\r\n");
      out.write("<tr><td>17.\tAt the foot of a mountain the elevation of its summit is 45 degrees. After ascending one KM towards the mountain upon an incline of 30 degrees, the elevation changes to 60 degrees. Find the Height of the mountain?<br> \r\n");
      out.write("A)1.333Km B)1.366Km C)1.233Km D)1.266Km E)None of these <br><br></tr></td>\r\n");
      out.write("<tr><td>18.\tThe average of a couple was 23Yrs when they were married 5Yrs ago.The avg age of the couple and a child, who was born during the interval, is 20Yrs now. How old is the child now ?\r\n");
      out.write("<br>A)2 Yrs B)4 Yrs C)3 Yrs D)1 Yrs E)None of these <br><br></tr></td>\r\n");
      out.write("<tr><td>19.\tTwo liters of a mixture of alcohol and water contain 10% water. This is added to 4 litres of another mixture containing 8% water and half a litre of water is then added to the whole. Find the percentage of water in the resulting mixture.\r\n");
      out.write("<br>A)17 3/11% B)15 3/13% C)14 12/13% D)15 9/13% E)None of these <br><br></tr></td>\r\n");
      out.write("<tr><td>20.\tEight chairs are numbered 1 to 8. Two women and Three men wish to occupy one chair each. First the women choose the chairs marked 1 to 4, and then the men occupy the remaining chairs. Find the possible number of arrangement. \r\n");
      out.write("<br>A)6C3 * 4C2 B)4C2 * 4P3 C)4P2 * 4P3 D)4P2 * 6P3 E)None of these </tr></td>\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr><td height=\"1\"><table width=\"800\" cellpadding=0 cellspacing=0>\r\n");
      out.write(" <tr><td class=fo >\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table cellpadding=0 cellspacing=0 width=\"800\" >\r\n");
      out.write("  <tr><td width=\"48\"><IMG height=36 src=\"m33.gif\" width=42 align=left ></td>\r\n");
      out.write("    <td class=fo width=\"800\">All Rights Reserved. </td>\r\n");
      out.write("    <td align=right width=\"220\" class=fo><IMG height=36 src=\"m35.gif\" width=214 ></td></tr>\r\n");
      out.write(" </table></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</table></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</center>\r\n");
      out.write("</BODY>\r\n");
      out.write("</HTML>\r\n");
}
catch(Exception e)
{}

      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
