/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.26
 * Generated at: 2016-04-12 06:34:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.Dbconnection.Dbconnection;

public final class createexam_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

 Connection con=null;
    PreparedStatement jre,aci;
    ResultSet jrs,rs;

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

try
{
	
	 String vv=request.getParameter("v");

	 con=Dbconnection.getConnection();

	jre=con.prepareStatement("select count(*) from jkcdata where status=0");
        jrs=jre.executeQuery();
		jrs.next();
		
aci=con.prepareStatement("select count(*) from exampaper");
        rs=aci.executeQuery();
		rs.next();
		int i=rs.getInt(1);
		        


      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title></title>\r\n");
      out.write("<link rel=stylesheet href=st.css type=text/css>\r\n");
      out.write("<LINK \r\n");
      out.write("media=screen,projection,print \r\n");
      out.write("href=\"dropdown/main.css\" type=text/css \r\n");
      out.write("rel=stylesheet>\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("\r\n");
      out.write("function time(field)\r\n");
      out.write("\t{\r\n");
      out.write("\t    \r\n");
      out.write("\t     var str=field.value;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t if(str.length>5)\r\n");
      out.write("\t\t { \r\n");
      out.write("\t\t\t  alert(\"The Time you entered is invalid\");\r\n");
      out.write("\t\t\t  return false;\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t var str1=str.charAt(0)+str.charAt(1);\r\n");
      out.write("\t\t var str2=str.charAt(3)+str.charAt(4);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t if(str.charAt(2)!=':')\r\n");
      out.write("\t\t {\r\n");
      out.write("               alert(\"The time you enterd is not in correct format\");\r\n");
      out.write("\t\t\t   return false;\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t if(((str1)>=0 && (str1)<=12)&& ((str2)>=0 && (str2)<60))\r\n");
      out.write("\t\t{}else{\r\n");
      out.write("\t\t\t alert(\"The time you entered is invalid\");\r\n");
      out.write("\t\t\t return false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("function numberformat(field,alerttxt)\r\n");
      out.write("\t{\r\n");
      out.write("         var str=field.value;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t for( var i=0;i<str.length;i++)\r\n");
      out.write("\t\t {\r\n");
      out.write("\t\t\t   \r\n");
      out.write("               if(  !(str.charAt(i)>='0'&&str.charAt(i)<='9'  ))\r\n");
      out.write("\t\t       {\r\n");
      out.write("\t\t\t     alert(alerttxt);\r\n");
      out.write("\t\t\t    return false;\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t  }\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function check()\r\n");
      out.write("\t{\r\n");
      out.write("\t    var str1=document.getElementById(\"noq\").value;\r\n");
      out.write("        var str2=document.getElementById(\"key\").value;\r\n");
      out.write("      \r\n");
      out.write("        if(str1!=str2.length)\r\n");
      out.write("\t\t{ alert(\"No of questions and Key string does not match\");\r\n");
      out.write("\t\t  return false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfor(var i=0;i<str2.length;i++)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(str2.charAt(i)=='A'||str2.charAt(i)=='B'||str2.charAt(i)=='C'||str2.charAt(i)=='D')\r\n");
      out.write("\t\t\t{}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"The Key string should contain either A or B or C or D\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("function validate_required(field,alerttxt)\r\n");
      out.write("{\r\n");
      out.write("with(field)\r\n");
      out.write("{\r\n");
      out.write("if (value==null||value==\"\")\r\n");
      out.write("  {alert(alerttxt);return false}\r\n");
      out.write("else {return true}\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function validate_form(thisform)\r\n");
      out.write("{\r\n");
      out.write("with (thisform)\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("if (validate_required(top,\"Topic field must be filled out!\")==false)\r\n");
      out.write("  {top.focus();return false}\r\n");
      out.write("if (validate_required(noq,\"Number of Questions field must be filled out!\")==false)\r\n");
      out.write("  {noq.focus();return false}\r\n");
      out.write("if (validate_required(uf,\"Enter filename field must be filled out!\")==false)\r\n");
      out.write("  {uf.focus();return false}\r\n");
      out.write("if (validate_required(key,\"Key field must be filled out!\")==false)\r\n");
      out.write("  {key.focus();return false}\r\n");
      out.write("if (validate_required(active,\"Activation time field must be filled out!\")==false)\r\n");
      out.write("  {active.focus();return false}\r\n");
      out.write("if (validate_required(dur,\"Duration field must be filled out!\")==false)\r\n");
      out.write("  {dur.focus();return false}\r\n");
      out.write("if(numberformat(noq,\"only numbers are allowed in no of questions field\")==false)\r\n");
      out.write("\t{noq.focus();return false}\r\n");
      out.write("if(numberformat(dur,\"only numbers are allowed in duration field\")==false)\r\n");
      out.write("\t{dur.focus();return false}\r\n");
      out.write("\r\n");
      out.write("if(check()==false)\r\n");
      out.write("\t{key.focus();return false}\r\n");
      out.write("if(time(active)==false)\r\n");
      out.write("\t{active.focus();return false}\r\n");
      out.write("}}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<BODY >\r\n");
      out.write("\r\n");
      out.write("<table  valign=\"top\" cellpadding=0 cellspacing=0 width=\"800\"  align=center  bordercolor=\"#2A8DCC\" >\r\n");
      out.write(" <tr><td valign=top class=to width=\"800\" bgcolor=\"0F4F8D\">\r\n");
      out.write("<table width=\"800\" cellpadding=0 cellspacing=0 height=\"144\" >\r\n");
      out.write(" <tr><td width=\"800\" height=\"144\"><IMG id=IMG1 height=144 src=\"img/sri1.gif\" width=\"100%\" ></td></tr>\r\n");
      out.write("<tr><td width=\"800\" height=\"10\"><IMG height=40 src=\"img/m021.gif\" width=326 ></td></tr></table></tr>\r\n");
      out.write("\r\n");
      out.write(" <tr><td><table width=\"800\" border=\"1\" bordercolor=\"#0077c0\" height=\"500\" bgcolor=white>\r\n");
      out.write("<tr><td valign=left width=\"200\" class=ma><h5></h5>\r\n");
      out.write("\r\n");
      out.write("<table cellSpacing=0 cellPadding=0 width=\"100%\" border=0>\r\n");
      out.write("<tr><td vAlign=center align=middle colSpan=2>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr><td height=15></td></tr>\r\n");
      out.write("<TR><TD vAlign=center align=middle ><IMG height=1 src=\"img/D2_Blueline.gif\" width=\"98%\"></TD></TR>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center height=22>&nbsp;&nbsp;<IMG height=5\r\n");
      out.write("                              src=\"img/D4_redbullet.gif\" \r\n");
      out.write("                             width=5>&nbsp; \r\n");
      out.write("                            <FONT height=10\r\n");
      out.write("                              face=\"Verdana, Arial, Helvetica, sans-serif\" \r\n");
      out.write("                              color=#ffffff size=2>\r\n");
      out.write("                             <A class=links href=\"jkcupdateprofile.jsp?v=0\">Update profile</A></FONT></TD></TR>\r\n");
      out.write("\r\n");
      out.write("<TR> <TD vAlign=center align=middle colSpan=2>\r\n");
      out.write("<IMG height=1 src=\"img/D2_Blueline.gif\" width=\"98%\"></TD></TR>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center height=22>&nbsp;&nbsp;<IMG height=5\r\n");
      out.write("                              src=\"img/D4_redbullet.gif\" \r\n");
      out.write("                             width=5>&nbsp; \r\n");
      out.write("                            <FONT \r\n");
      out.write("                              face=\"Verdana, Arial, Helvetica, sans-serif\" \r\n");
      out.write("                              color=#ffffff size=2>\r\n");
      out.write("                             <a class=links href=\"jkcadminchgpwd.jsp?v=0\">Changepassword</FONT></TD></TR>\r\n");
      out.write("\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center align=middle colSpan=2><IMG \r\n");
      out.write("                              height=1\r\n");
      out.write("                              src=\"img/D2_Blueline.gif\" \r\n");
      out.write("                              width=\"98%\"></TD></TR>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center height=22>&nbsp;&nbsp;<IMG height=5\r\n");
      out.write("                              src=\"img/D4_redbullet.gif\" \r\n");
      out.write("                             width=5>&nbsp; \r\n");
      out.write("                            <FONT \r\n");
      out.write("                              face=\"Verdana, Arial, Helvetica, sans-serif\" \r\n");
      out.write("                              color=#ffffff size=2>\r\n");
      out.write("                             <a class=links href=\"sturequest.jsp?v=0\">Student request <font color=\"orange\">       (");
      out.print(jrs.getInt(1));
      out.write(")</font></FONT></TD></TR>\r\n");
      out.write("\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center align=middle colSpan=2><IMG \r\n");
      out.write("                              height=1\r\n");
      out.write("                              src=\"img/D2_Blueline.gif\" \r\n");
      out.write("                              width=\"98%\"></TD></TR>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center height=22>&nbsp;&nbsp;<IMG height=5\r\n");
      out.write("                              src=\"img/D4_redbullet.gif\" \r\n");
      out.write("                             width=5>&nbsp; \r\n");
      out.write("                            <FONT \r\n");
      out.write("                              face=\"Verdana, Arial, Helvetica, sans-serif\" \r\n");
      out.write("                              color=#ffffff size=2>\r\n");
      out.write("                             <a class=links href=\"notifications.jsp?v=0\">Notifications</FONT></TD></TR>\r\n");
      out.write("\r\n");
      out.write("<TR> <TD vAlign=center align=middle colSpan=2>\r\n");
      out.write("<IMG height=1 src=\"img/D2_Blueline.gif\" width=\"98%\"></TD></TR>\r\n");
      out.write("\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center height=22>&nbsp;&nbsp;<IMG height=5\r\n");
      out.write("                              src=\"img/D4_redbullet.gif\" \r\n");
      out.write("                             width=5>&nbsp; \r\n");
      out.write("                            <FONT \r\n");
      out.write("                              face=\"Verdana, Arial, Helvetica, sans-serif\" \r\n");
      out.write("                              color=#ffffff size=2>\r\n");
      out.write("                             <a class=links href=\"jkccomp.jsp?v=0\">Companies list</FONT></TD></TR>\r\n");
      out.write("\r\n");
      out.write("<TR><TD vAlign=center align=middle colSpan=2>\r\n");
      out.write("<IMG height=1 src=\"img/D2_Blueline.gif\" width=\"98%\"></TD></TR>\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center height=22>&nbsp;&nbsp;<IMG height=5\r\n");
      out.write("                              src=\"img/D4_redbullet.gif\" \r\n");
      out.write("                             width=5>&nbsp; \r\n");
      out.write("                            <FONT \r\n");
      out.write("                              face=\"Verdana, Arial, Helvetica, sans-serif\" \r\n");
      out.write("                              color=#ffffff size=2>\r\n");
      out.write("                             <a class=links href=\"jkcstu.jsp?v=0\">Selected students</FONT></TD></TR>\r\n");
      out.write("<TR> <TD vAlign=center align=middle colSpan=2>\r\n");
      out.write("<IMG height=1 src=\"img/D2_Blueline.gif\" width=\"98%\"></TD></TR>\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center height=22>&nbsp;&nbsp;<IMG height=5\r\n");
      out.write("                              src=\"img/D4_redbullet.gif\" \r\n");
      out.write("                             width=5>&nbsp; \r\n");
      out.write("                            <FONT \r\n");
      out.write("                              face=\"Verdana, Arial, Helvetica, sans-serif\" \r\n");
      out.write("                              color=#ffffff size=2>\r\n");
      out.write("                             <a class=links href=\"jkccolleges.jsp?v=0\">JKC Colleges</FONT></TD></TR>\r\n");
      out.write("<TR> <TD vAlign=center align=middle colSpan=2>\r\n");
      out.write("<IMG height=1 src=\"img/D2_Blueline.gif\" width=\"98%\"></TD></TR>\r\n");
      out.write("\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center height=22>&nbsp;&nbsp;<IMG height=5\r\n");
      out.write("                              src=\"img/D4_redbullet.gif\" \r\n");
      out.write("                             width=5>&nbsp; \r\n");
      out.write("                            <FONT \r\n");
      out.write("                              face=\"Verdana, Arial, Helvetica, sans-serif\" \r\n");
      out.write("                              color=#ffffff size=2>\r\n");
      out.write("                             <a class=links href=\"createexam.jsp?v=0\">Create Exam paper</FONT></TD></TR>\r\n");
      out.write("<TR> <TD vAlign=center align=middle colSpan=2>\r\n");
      out.write("<IMG height=1 src=\"img/D2_Blueline.gif\" width=\"98%\"></TD></TR>\r\n");
      out.write("\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center height=22>&nbsp;&nbsp;<IMG height=5\r\n");
      out.write("                              src=\"img/D4_redbullet.gif\" \r\n");
      out.write("                             width=5>&nbsp; \r\n");
      out.write("                            <FONT \r\n");
      out.write("                              face=\"Verdana, Arial, Helvetica, sans-serif\" \r\n");
      out.write("                              color=#ffffff size=2>\r\n");
      out.write("                             <a class=links href=\"jkcschedule.jsp?v=0\">Exam Schedule</FONT></TD></TR>\r\n");
      out.write("<TR> <TD vAlign=center align=middle colSpan=2>\r\n");
      out.write("<IMG height=1 src=\"img/D2_Blueline.gif\" width=\"98%\"></TD></TR>\r\n");
      out.write("\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center height=22>&nbsp;&nbsp;<IMG height=5\r\n");
      out.write("                              src=\"img/D4_redbullet.gif\" \r\n");
      out.write("                             width=5>&nbsp; \r\n");
      out.write("                            <FONT \r\n");
      out.write("                              face=\"Verdana, Arial, Helvetica, sans-serif\" \r\n");
      out.write("                              color=#ffffff size=2>\r\n");
      out.write("                             <a class=links href=\"jkcresults.jsp?v=0\">Results</FONT></TD></TR>\r\n");
      out.write("<TR> <TD vAlign=center align=middle colSpan=2>\r\n");
      out.write("<IMG height=1 src=\"img/D2_Blueline.gif\" width=\"98%\"></TD></TR>\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center height=22>&nbsp;&nbsp;<IMG height=5\r\n");
      out.write("                              src=\"img/D4_redbullet.gif\" \r\n");
      out.write("                             width=5>&nbsp; \r\n");
      out.write("                            <FONT \r\n");
      out.write("                              face=\"Verdana, Arial, Helvetica, sans-serif\" \r\n");
      out.write("                              color=#ffffff size=2>\r\n");
      out.write("                             <a class=links href=\"jkcreglist.jsp?v=0\">JKC Selected Students</FONT></TD></TR>\r\n");
      out.write("<TR> <TD vAlign=center align=middle colSpan=2>\r\n");
      out.write("<IMG height=1 src=\"img/D2_Blueline.gif\" width=\"98%\"></TD></TR>\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center height=22>&nbsp;&nbsp;<IMG height=5\r\n");
      out.write("                              src=\"img/D4_redbullet.gif\" \r\n");
      out.write("                             width=5>&nbsp; \r\n");
      out.write("                            <FONT \r\n");
      out.write("                              face=\"Verdana, Arial, Helvetica, sans-serif\" \r\n");
      out.write("                              color=#ffffff size=2>\r\n");
      out.write("                             <a class=links href=\"logout.jsp?v=0\">Logout</FONT></TD></TR>\r\n");
      out.write("\r\n");
      out.write("<TR><TD vAlign=center align=middle colSpan=2>\r\n");
      out.write("<IMG height=1 src=\"img/D2_Blueline.gif\" width=\"98%\"></TD></TR>\r\n");
      out.write("\r\n");
      out.write("</font></table>\r\n");
      out.write("<td width=\"600\">\r\n");
      out.write("<table width=\"600\" height=\"600\">\r\n");
      out.write("\r\n");
      out.write("<tr><td height=30></td></tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form action=\"createdhtmlexam.jsp\" method=\"post\">\r\n");
      out.write("<tr><td align=center>");
if(i!=0)
	{
	if(vv.equals("1")){}else{
      out.write("<font color=green size=4px>Delete the present exampaper</font>\r\n");
      out.write("\t   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type=submit name=r1 value=\"delete\">\r\n");
      out.write("\t\r\n");
      out.write("\t");
}}
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t</td></tr>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t <tr><td> ");
if(vv.equals("1")){
      out.write("\r\n");
      out.write("<center><font color=green size=4px>Exam created</font></center>");
}
      out.write('\r');
      out.write('\n');
if(vv.equals("2")){
      out.write("\r\n");
      out.write("<center><font color=green size=4px>Successfully deleted</font></center>");
}
      out.write("</tr></td>\r\n");
      out.write("<tr><td height=\"30\"></td></tr><tr><td height=\"30\"><center><h3><font color=\"#0077c0\">CREATE EXAM</font></h3>\r\n");
      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("<tr><td height=\"10\"></td></tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form onsubmit=\"return validate_form(this)\" action=\"createdhtmlexam.jsp\"  method=\"post\">\r\n");
      out.write("\r\n");
      out.write("<tr><td>Topic </td><td><input type=\"text\" name=\"top\" size=20>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("Number of questions</td><td><input type=\"text\" name=\"noq\" size=20 ></td></tr>\r\n");
      out.write("<tr><td height=10></td></tr>\r\n");
      out.write("<tr><td>Enter File Name</td><td><input type=\"text\" name=\"uf\" size=0 ></td></tr><tr><td height=10></td></tr>\r\n");
      out.write("<tr><td>Key String</td><td><input type=\"text\" name=\"key\" size=40></td></tr><tr><td height=10></td></tr>\r\n");
      out.write("<tr><td>Activation Time </td><td><input type=\"text\" name=\"active\" size=20>HH:MM&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("Duration</td><td><input type=\"text\" name=\"dur\" size=20 ></td></tr>\r\n");
      out.write("<tr><td height=10></td></tr>\r\n");
      out.write("\r\n");
      out.write("<tr><td height=\"10\"></td></tr>\r\n");
if(i==0){if(vv.equals("1")){}else{
      out.write("\r\n");
      out.write("<tr><td colspan=2 align=center>\r\n");
      out.write("<input type=\"submit\" size=5 name=r1 value=Submit></td>\r\n");
      out.write("<td align=left><input type=\"reset\" name=r1 value=\"reset\">\r\n");
}}
      out.write("\r\n");
      out.write("</td></tr><tr><td height=\"24\"></td>\r\n");
      out.write("<tr><td height=\"200\"></td></tr>\r\n");
      out.write("</table></form></center></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</td></tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr><td height=\"1\"><table width=\"800\" cellpadding=0 cellspacing=0>\r\n");
      out.write(" <tr><td class=fo >\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table cellpadding=0 cellspacing=0 width=\"800\" >\r\n");
      out.write("  <tr><td width=\"48\"><IMG height=36 src=\"img/m33.gif\" width=42 align=left ></td>\r\n");
      out.write("    <td class=fo width=\"800\">All Rights Reserved. </td>\r\n");
      out.write("    <td align=right width=\"220\" class=fo><IMG height=36 src=\"img/m35.gif\" width=214 ></td></tr>\r\n");
      out.write(" </table></td></tr>\r\n");
      out.write("</td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</center>\r\n");
      out.write("</BODY>\r\n");
      out.write("</HTML>\r\n");

}
catch(Exception e)
{
	out.println(e);
}

      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
