/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.26
 * Generated at: 2016-04-26 03:37:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.Dbconnection.Dbconnection;

public final class onlineletter_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


Connection con=null;
Statement stmt1,stmt2,stmt3;

//ResultSet rs=null;
String rg1,rg2,rg3,rg4,rg5,rg6,rg7,rg8,rg9,rg10,rg11,rg12,rg13,rg14,rg15,rg16,rg17,rg18,rg19,rg20,rg21;

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

  rg1=request.getParameter("inname");
  rg2=request.getParameter("code");
  rg3=request.getParameter("address");
  rg4=request.getParameter("city");
  rg5=request.getParameter("pin");
  rg6=request.getParameter("state");
  rg7=request.getParameter("tel");
  rg8=request.getParameter("fax");
  rg9=request.getParameter("email");
  rg10=request.getParameter("website");
 String est=request.getParameter("esttdt");
  String dd = est.substring(0,2);
  String mm = est.substring(3,5);
  String yy = est.substring(6,10);
  rg11=dd+"-"+mm+"-"+yy;
  rg12=request.getParameter("affil");
  rg13=request.getParameter("ptitle");
  rg14=request.getParameter("pname");
  rg15=request.getParameter("pdesig");
  rg16=request.getParameter("faculties");
  rg17=request.getParameter("teachstaff");
  rg18=request.getParameter("admstaff");
  rg19=request.getParameter("techstaff");
  rg20=request.getParameter("students");
  rg21=request.getParameter("progoffered");
 
  

 try
 {
	 con=Dbconnection.getConnection();
	 
  String m=rg13;
    m=m+rg14;
  String s="insert into colleges values('"+rg1+"','"+rg2+"','"+rg11+"','"+rg12+"','"+rg14+"','"+rg15+"','requesting','notgiven','no')";
  stmt1=con.createStatement();  
  out.println(s);
  stmt1.executeUpdate(s);
  
  
  
  
  stmt2=con.createStatement();
  stmt2.executeUpdate("insert into ccdetails values('"+rg2+"','"+rg3+"','"+rg4+"','"+rg5+"','"+rg6+"','"+rg7+"','"+rg8+"','"+rg9+"','"+rg10+"')");


  stmt3=con.createStatement();
  
  stmt3.executeUpdate("insert into colldetails values('"+rg2+"','"+rg16+"','"+rg17+"','"+rg18+"','"+rg19+"','"+rg20+"','"+rg21+"')");
  
  response.sendRedirect("message.jsp?");
  
      out.write("\r\n");
      out.write(" <html>\r\n");
      out.write(" <body>\r\n");
      out.write(" \r\n");
      out.write(" </body></html>\r\n");

} 
 catch(Exception e)
    {
        out.println(e);
     }

      out.write("\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
