/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.26
 * Generated at: 2016-03-17 09:10:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class staffdetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


try
{
  String vv=request.getParameter("v");
 String uid=(String)session.getAttribute("uid1");
   if(uid!=null)
  {}
else
{
      response.sendRedirect("index.jsp");
  }
  
      out.write('\r');
      out.write('\n');
session.setAttribute("uid1",uid);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title></title>\r\n");
      out.write("<link rel=stylesheet href=st.css type=text/css>\r\n");
      out.write("<LINK \r\n");
      out.write("media=screen,projection,print \r\n");
      out.write("href=\"dropdown/main.css\" type=text/css \r\n");
      out.write("rel=stylesheet>\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function checkemail()\r\n");
      out.write("{\r\n");
      out.write("var str=document.getElementById(\"emailid\").value;\r\n");
      out.write("\r\n");
      out.write("var filter=/^([\\w-]+(?:\\.[\\w-]+)*)@((?:[\\w-]+\\.)*\\w[\\w-]{0,66})\\.([a-z]{2,6}(?:\\.[a-z]{2})?)$/i\r\n");
      out.write("if (!(filter.test(str)))\r\n");
      out.write(" {\r\n");
      out.write("  alert(\"Please input a valid email address!\")\r\n");
      out.write("  return false;\r\n");
      out.write(" } \r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("function len()\r\n");
      out.write("{\r\n");
      out.write("    var j=document.getElementById(\"fn\").value;\r\n");
      out.write("\tfor(var i=0;i<j.length;i++)\r\n");
      out.write("\t{\r\n");
      out.write("\t   if(!((j.charAt(i)>='A'&&j.charAt(i)<='Z')||(j.charAt(i)>='a'&&j.charAt(i)<='z')||(j.charAt(i)==' ')))\r\n");
      out.write("\t    {\r\n");
      out.write("\t\t alert(\"only characters are allowed\");\r\n");
      out.write("\t\t document.getElementById(\"fn\").focus();\r\n");
      out.write("\t\t break;\r\n");
      out.write("\t    }\r\n");
      out.write("\t}\r\n");
      out.write("\tif(j.length>=15)\r\n");
      out.write("   {\r\n");
      out.write("\t  \r\n");
      out.write("\t         alert(\"The size of the first name should be less than 15:\");\r\n");
      out.write("              document.getElementById(\"fn\").focus();\r\n");
      out.write("\t  }\r\n");
      out.write("\t \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function len1()\r\n");
      out.write("{\r\n");
      out.write("    var j=document.getElementById(\"ln\").value;\r\n");
      out.write("\tfor(var i=0;i<j.length;i++)\r\n");
      out.write("\t{\r\n");
      out.write("\t   if(!((j.charAt(i)>='A'&&j.charAt(i)<='Z')||(j.charAt(i)>='a'&&j.charAt(i)<='z')||(j.charAt(i)==' ')))\r\n");
      out.write("\t    {\r\n");
      out.write("\t\t alert(\"only characters are allowed\");\r\n");
      out.write("\t\t document.getElementById(\"ln\").focus();\r\n");
      out.write("\t\t break;\r\n");
      out.write("\t    }\r\n");
      out.write("\t}\r\n");
      out.write("\tif(j.length>=15)\r\n");
      out.write("   {\r\n");
      out.write("\t  \r\n");
      out.write("\t         alert(\"The size of the last name should be less than 15:\");\r\n");
      out.write("              document.getElementById(\"ln\").focus();\r\n");
      out.write("\t  }\r\n");
      out.write("\t \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function len2()\r\n");
      out.write("{\r\n");
      out.write("    var j=document.getElementById(\"id\").value;\r\n");
      out.write("\tif(j.length>=12)\r\n");
      out.write("   {\r\n");
      out.write("\t  \r\n");
      out.write("\t         alert(\"The size of the registration-id should be less than 12:\");\r\n");
      out.write("               document.getElementById(\"id\").focus();     \r\n");
      out.write("\t  }\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function len3()\r\n");
      out.write("{\r\n");
      out.write("    var j=document.getElementById(\"degree\").value;\r\n");
      out.write("\tfor(var i=0;i<j.length;i++)\r\n");
      out.write("\t{\r\n");
      out.write("\t   if(!((j.charAt(i)>='A'&&j.charAt(i)<='Z')||(j.charAt(i)>='a'&&j.charAt(i)<='z')||(j.charAt(i)==' ')\r\n");
      out.write("\t\t   ||(j.charAt(i)=='.')))\r\n");
      out.write("\t    {\r\n");
      out.write("\t\t alert(\"only characters are allowed\");\r\n");
      out.write("\t\t document.getElementById(\"degree\").focus();\r\n");
      out.write("\t\t break;\r\n");
      out.write("\t    }\r\n");
      out.write("\t}\r\n");
      out.write("\tif(j.length>=15)\r\n");
      out.write("   {\r\n");
      out.write("\t  \r\n");
      out.write("\t         alert(\"The size of the first name should be less than 15:\");\r\n");
      out.write("              document.getElementById(\"degree\").focus();\r\n");
      out.write("\t  }\r\n");
      out.write("\t \r\n");
      out.write("}\r\n");
      out.write("function len4()\r\n");
      out.write("{\r\n");
      out.write("    var j=document.getElementById(\"subject\").value;\r\n");
      out.write("\tfor(var i=0;i<j.length;i++)\r\n");
      out.write("\t{\r\n");
      out.write("\t   if(!((j.charAt(i)>='A'&&j.charAt(i)<='Z')||(j.charAt(i)>='a'&&j.charAt(i)<='z')||(j.charAt(i)==' ')))\r\n");
      out.write("\t    {\r\n");
      out.write("\t\t alert(\"only characters are allowed\");\r\n");
      out.write("\t\t document.getElementById(\"subject\").focus();\r\n");
      out.write("\t\t break;\r\n");
      out.write("\t    }\r\n");
      out.write("\t}\r\n");
      out.write("\tif(j.length>=15)\r\n");
      out.write("   {\r\n");
      out.write("\t  \r\n");
      out.write("\t         alert(\"The size of the first name should be less than 15:\");\r\n");
      out.write("              document.getElementById(\"subject\").focus();\r\n");
      out.write("\t  }\r\n");
      out.write("\t \r\n");
      out.write("}\r\n");
      out.write("function len10()\r\n");
      out.write("{\r\n");
      out.write("    var j=document.getElementById(\"contactno\").value;\r\n");
      out.write("\tif(j.length>=15)\r\n");
      out.write("   {\r\n");
      out.write("\t  \r\n");
      out.write("\t         alert(\"The size of the contact number should be less than 15:\");\r\n");
      out.write("     \r\n");
      out.write("\t   document.getElementById(\"contactno\").focus();\r\n");
      out.write("\t   }\r\n");
      out.write("}\r\n");
      out.write("function len11()\r\n");
      out.write("{\r\n");
      out.write("    var j=document.getElementById(\"emailid\").value;\r\n");
      out.write("\tif(j.length>=25)\r\n");
      out.write("   {\r\n");
      out.write("\t  \r\n");
      out.write("\t         alert(\"The size of the emailid should be less than 25:\");\r\n");
      out.write("     \r\n");
      out.write("\t   document.getElementById(\"emailid\").focus();\r\n");
      out.write("\t   }\r\n");
      out.write("}\r\n");
      out.write("function len9()\r\n");
      out.write("{\r\n");
      out.write("    var j=document.getElementById(\"address\").value;\r\n");
      out.write("\tif(j.length>=40)\r\n");
      out.write("   {\r\n");
      out.write("\t  \r\n");
      out.write("\t         alert(\"The size of the address should be less than 40:\");\r\n");
      out.write("     \r\n");
      out.write("\t   document.getElementById(\"address\").focus();\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function len12()\r\n");
      out.write("{\r\n");
      out.write("    var j=document.getElementById(\"sal\").value;\r\n");
      out.write("\tvar c=0;\r\n");
      out.write("\tif(j.length>=15)\r\n");
      out.write("   {\r\n");
      out.write("\t  \r\n");
      out.write("\t         alert(\"The size of the Total salary should be less than 15:\");\r\n");
      out.write("     \r\n");
      out.write("\t  }\r\n");
      out.write("\t  for(i=0;i<j.length;i++)\r\n");
      out.write("\t{\r\n");
      out.write("       if(j.charAt(i)>='0'&&j.charAt(i)<='9')\r\n");
      out.write("        {}\r\n");
      out.write("\t   else\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t   c=1; \r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tif(c==1)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"characters are not allowed\");\r\n");
      out.write("\t\t document.getElementById(\"sal\").focus();\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function len13()\r\n");
      out.write("{\r\n");
      out.write("    var j=document.getElementById(\"classsal\").value;\r\n");
      out.write("\tvar c=0;\r\n");
      out.write("\tif(j.length>=15)\r\n");
      out.write("   {\r\n");
      out.write("\t  \r\n");
      out.write("\t         alert(\"The size of the sal of the day should be less than 15:\");\r\n");
      out.write("     \r\n");
      out.write("\t  }\r\n");
      out.write("\t  for(i=0;i<j.length;i++)\r\n");
      out.write("\t{\r\n");
      out.write("       if(j.charAt(i)>='0'&&j.charAt(i)<='9')\r\n");
      out.write("        {}\r\n");
      out.write("\t   else\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t   c=1; \r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tif(c==1)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"characters are not allowed\");\r\n");
      out.write("\t\t document.getElementById(\"classsal\").focus();\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function validate_required(field,alerttxt)\r\n");
      out.write("{\r\n");
      out.write("with(field)\r\n");
      out.write("{\r\n");
      out.write("if (value==null||value==\"\")\r\n");
      out.write("  {alert(alerttxt);return false}\r\n");
      out.write("else {return true}\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function validate_form(thisform)\r\n");
      out.write("{\r\n");
      out.write("with (thisform)\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("if (validate_required(id,\"Registration number field must be filled out!\")==false)\r\n");
      out.write("  {id.focus();return false}\r\n");
      out.write("if (validate_required(fn,\"First name field must be filled out!\")==false)\r\n");
      out.write("  {fn.focus();return false}\r\n");
      out.write("if (validate_required(ln,\"Surname field must be filled out!\")==false)\r\n");
      out.write("  {ln.focus();return false}\r\n");
      out.write("if (validate_required(degree,\"Degree field must be filled out!\")==false)\r\n");
      out.write("  {degree.focus();return false}\r\n");
      out.write("if (validate_required(subject,\"Subject field must be filled out!\")==false)\r\n");
      out.write("  {subject.focus();return false}\r\n");
      out.write("if (validate_required(sal,\"Total salary field must be filled out!\")==false)\r\n");
      out.write("  {sal.focus();return false}\r\n");
      out.write("if (validate_required(classsal,\"Salary per day must be filled out!\")==false)\r\n");
      out.write("  {classsal.focus();return false}\r\n");
      out.write("if (validate_required(address,\"Address field must be filled out!\")==false)\r\n");
      out.write("  {address.focus();return false}\r\n");
      out.write("if (validate_required(emailid,\"emai-id field must be filled out!\")==false)\r\n");
      out.write("  {emailid.focus();return false}\r\n");
      out.write("if (checkemail()==false)\r\n");
      out.write("  {emailid.focus();return false}\r\n");
      out.write("}}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<BODY bgcolor=\"#A9B1B9\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table  valign=\"top\" cellpadding=0 cellspacing=0 width=\"800\"  align=center  bordercolor=\"#2A8DCC\" >\r\n");
      out.write(" <tr><td valign=top class=to width=\"800\" bgcolor=\"0F4F8D\">\r\n");
      out.write("<table width=\"800\" cellpadding=0 cellspacing=0 height=\"144\" >\r\n");
      out.write(" <tr><td width=\"800\" height=\"144\"><IMG id=IMG1 height=144 src=\"img/sri1.gif\" width=\"100%\" ></td></tr>\r\n");
      out.write("<tr><td width=\"800\" height=\"10\"><IMG height=40 src=\"img/m021.gif\" width=326> </td></tr></table></tr>\r\n");
      out.write("\r\n");
      out.write("<tr><td><table width=\"800\" border=\"1\"  bordercolor=\"#2A8DCC\" bgcolor=white>\r\n");
      out.write("<tr><td valign=left width=\"200\" class=ma colspan=2>\r\n");
      out.write("\r\n");
      out.write("<table cellSpacing=0 cellPadding=0 width=\"100%\" border=0>\r\n");
      out.write("<tr><td vAlign=center align=middle colSpan=2>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr><td height=15></td></tr>\r\n");
      out.write("<TR><TD vAlign=center align=middle ><IMG height=1 src=\"img/D2_Blueline.gif\" width=\"98%\"></TD></TR>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center height=22>&nbsp;&nbsp;<IMG height=5\r\n");
      out.write("                              src=\"img/D4_redbullet.gif\" \r\n");
      out.write("                             width=5>&nbsp; \r\n");
      out.write("                            <FONT height=10\r\n");
      out.write("                              face=\"Verdana, Arial, Helvetica, sans-serif\" \r\n");
      out.write("                              color=#ffffff size=2>\r\n");
      out.write("                             <A class=links href=\"updateprofile.jsp?v=0\">Update profile</A></FONT></TD></TR>\r\n");
      out.write("\r\n");
      out.write("<TR> <TD vAlign=center align=middle colSpan=2>\r\n");
      out.write("<IMG height=1 src=\"img/D2_Blueline.gif\" width=\"98%\"></TD></TR>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center height=22>&nbsp;&nbsp;<IMG height=5\r\n");
      out.write("                              src=\"img/D4_redbullet.gif\" \r\n");
      out.write("                             width=5>&nbsp; \r\n");
      out.write("                            <FONT \r\n");
      out.write("                              face=\"Verdana, Arial, Helvetica, sans-serif\" \r\n");
      out.write("                              color=#ffffff size=2>\r\n");
      out.write("                             <a class=links href=\"changepassword.jsp?v=0\">Changepassword</FONT></TD></TR>\r\n");
      out.write("\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center align=middle colSpan=2><IMG \r\n");
      out.write("                              height=1\r\n");
      out.write("                              src=\"img/D2_Blueline.gif\" \r\n");
      out.write("                              width=\"98%\"></TD></TR>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center height=22>&nbsp;&nbsp;<IMG height=5\r\n");
      out.write("                              src=\"img/D4_redbullet.gif\" \r\n");
      out.write("                             width=5>&nbsp; \r\n");
      out.write("                            <FONT \r\n");
      out.write("                              face=\"Verdana, Arial, Helvetica, sans-serif\" \r\n");
      out.write("                              color=#ffffff size=2>\r\n");
      out.write("                             <a class=links href=\"addstu.jsp?v=0\">Student Details</FONT></TD></TR>\r\n");
      out.write("\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center align=middle colSpan=2><IMG \r\n");
      out.write("                              height=1\r\n");
      out.write("                              src=\"img/D2_Blueline.gif\" \r\n");
      out.write("                              width=\"98%\"></TD></TR>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center height=22>&nbsp;&nbsp;<IMG height=5\r\n");
      out.write("                              src=\"img/D4_redbullet.gif\" \r\n");
      out.write("                             width=5>&nbsp; \r\n");
      out.write("                            <FONT \r\n");
      out.write("                              face=\"Verdana, Arial, Helvetica, sans-serif\" \r\n");
      out.write("                              color=#ffffff size=2>\r\n");
      out.write("                             <a class=links href=\"deleteid.jsp?v=0\">Delete Details</FONT></TD></TR>\r\n");
      out.write("\r\n");
      out.write("<TR> <TD vAlign=center align=middle colSpan=2>\r\n");
      out.write("<IMG height=1 src=\"img/D2_Blueline.gif\" width=\"98%\"></TD></TR>\r\n");
      out.write("\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center height=22>&nbsp;&nbsp;<IMG height=5\r\n");
      out.write("                              src=\"img/D4_redbullet.gif\" \r\n");
      out.write("                             width=5>&nbsp; \r\n");
      out.write("                            <FONT \r\n");
      out.write("                              face=\"Verdana, Arial, Helvetica, sans-serif\" \r\n");
      out.write("                              color=#ffffff size=2>\r\n");
      out.write("                             <a class=links href=\"addmarks.jsp?v=0\">Marks Details</FONT></TD></TR>\r\n");
      out.write("\r\n");
      out.write("<TR><TD vAlign=center align=middle colSpan=2>\r\n");
      out.write("<IMG height=1 src=\"img/D2_Blueline.gif\" width=\"98%\"></TD></TR>\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center height=22>&nbsp;&nbsp;<IMG height=5\r\n");
      out.write("                              src=\"img/D4_redbullet.gif\" \r\n");
      out.write("                             width=5>&nbsp; \r\n");
      out.write("                            <FONT \r\n");
      out.write("                              face=\"Verdana, Arial, Helvetica, sans-serif\" \r\n");
      out.write("                              color=#ffffff size=2>\r\n");
      out.write("                             <a class=links href=\"addatt.jsp?v=0\">Attendance Details</FONT></TD></TR>\r\n");
      out.write("<TR> <TD vAlign=center align=middle colSpan=2>\r\n");
      out.write("<IMG height=1 src=\"img/D2_Blueline.gif\" width=\"98%\"></TD></TR>\r\n");
      out.write("\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center height=22>&nbsp;&nbsp;<IMG height=5\r\n");
      out.write("                              src=\"img/D4_redbullet.gif\" \r\n");
      out.write("                             width=5>&nbsp; \r\n");
      out.write("                            <FONT \r\n");
      out.write("                              face=\"Verdana, Arial, Helvetica, sans-serif\" \r\n");
      out.write("                              color=#ffffff size=2>\r\n");
      out.write("                             <a class=links href=\"staffdetails.jsp?v=0\">Enter Staff Details</FONT></TD></TR>\r\n");
      out.write("<TR> <TD vAlign=center align=middle colSpan=2>\r\n");
      out.write("<IMG height=1 src=\"img/D2_Blueline.gif\" width=\"98%\"></TD></TR>\r\n");
      out.write("\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center height=22>&nbsp;&nbsp;<IMG height=5\r\n");
      out.write("                              src=\"img/D4_redbullet.gif\" \r\n");
      out.write("                             width=5>&nbsp; \r\n");
      out.write("                            <FONT \r\n");
      out.write("                              face=\"Verdana, Arial, Helvetica, sans-serif\" \r\n");
      out.write("                              color=#ffffff size=2>\r\n");
      out.write("                             <a class=links href=\"scholarship.jsp?v=0\">Scholarship Details</FONT></TD></TR>\r\n");
      out.write("<TR> <TD vAlign=center align=middle colSpan=2>\r\n");
      out.write("<IMG height=1 src=\"img/D2_Blueline.gif\" width=\"98%\"></TD></TR>\r\n");
      out.write("\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center height=22>&nbsp;&nbsp;<IMG height=5\r\n");
      out.write("                              src=\"img/D4_redbullet.gif\" \r\n");
      out.write("                             width=5>&nbsp; \r\n");
      out.write("                            <FONT \r\n");
      out.write("                              face=\"Verdana, Arial, Helvetica, sans-serif\" \r\n");
      out.write("                              color=#ffffff size=2>\r\n");
      out.write("                             <a class=links href=\"payroll.jsp?v=0\">Payroll System</FONT></TD></TR>\r\n");
      out.write("<TR> <TD vAlign=center align=middle colSpan=2>\r\n");
      out.write("<IMG height=1 src=\"img/D2_Blueline.gif\" width=\"98%\"></TD></TR>\r\n");
      out.write("\r\n");
      out.write("<TR>\r\n");
      out.write("                            <TD vAlign=center height=22>&nbsp;&nbsp;<IMG height=5\r\n");
      out.write("                              src=\"img/D4_redbullet.gif\" \r\n");
      out.write("                             width=5>&nbsp; \r\n");
      out.write("                            <FONT \r\n");
      out.write("                              face=\"Verdana, Arial, Helvetica, sans-serif\" \r\n");
      out.write("                              color=#ffffff size=2>\r\n");
      out.write("                             <a class=links href=\"logout.jsp?v=0\">Logout</FONT></TD></TR>\r\n");
      out.write("\r\n");
      out.write("<TR><TD vAlign=center align=middle colSpan=2>\r\n");
      out.write("<IMG height=1 src=\"img/D2_Blueline.gif\" width=\"98%\"></TD></TR>\r\n");
      out.write("\r\n");
      out.write("</font></table>\r\n");
      out.write("</td>\r\n");
      out.write("<td  width=600>\r\n");
      out.write("\r\n");
      out.write("<table width=100% height=18 align=top>\r\n");
      out.write("<tr><td height=15></td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td bgcolor=\"0077c0\" width=\"33%\" align=center><a style=\"color: white\" class=link1 href=\"staffdetails.jsp?v=0\">Add Staff Details</a></td>\r\n");
      out.write("<td bgcolor=\"0077c0\" width=\"33%\" align=center><a style=\"color: white\" class=link1  href=\"updatestaff.jsp?v=0\">Update Staff Details</a></td>\r\n");
      out.write("<td bgcolor=\"0077c0\" width=\"33%\" align=center><a style=\"color: white\" class=link1  href=\"viewstaff1.jsp?v=0\">View Staff Details</a></td>\r\n");
      out.write("\r\n");
      out.write("<tr><td height=50></td></tr></table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table align=center>\r\n");
      out.write("<tr><td height=\"10\"></td></tr>\r\n");
      out.write("<tr><td align=\"center\">");
if(vv.equals("1")){
      out.write("<font color=\"green\" size=\"4px\">Record updated</font>");
}
         if(vv.equals("2")){
      out.write("<font color=\"red\" size=\"4px\">Already the registration id-exists</font>");
}
      out.write("</td></tr>\r\n");
      out.write("\r\n");
      out.write("<tr><td height=\"10\"></td></tr>\r\n");
      out.write("<tr><td><form onsubmit=\"return validate_form(this)\" action=\"staffinsert.jsp\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("<table border=0  align=center height=\"578\">\r\n");
      out.write("<caption><h4><u><b><font color=#336699>ADD NEW STAFF </font></b></u></h4></caption>\r\n");
      out.write("<tr><td height=\"25\">FirstName:</td><td height=\"25\"><input type=text size=25 name=\"fn\" onBlur=\"len()\"></td><td height=\"25\">LastName:</td><td height=\"25\"><input type=text size=25 name=\"ln\" onBlur=\"len1()\"></td></tr><tr><td height=\"10\"></td></tr>\r\n");
      out.write("<tr><td height=\"25\">Registration ID:</td><td height=\"25\"><input type=text  name=\"id\" onBlur=\"len2()\"></td></tr><tr><td height=\"10\"></td></tr>\r\n");
      out.write("<tr><td height=\"25\">Gender</td><td><input type=\"radio\" name=\"gender\" value=\"male\">Male&nbsp;&nbsp;<input type=\"radio\" name=\"gender\" value=\"female\">Female</td></tr><tr><td height=\"10\"></td></tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr><td height=\"25\" width=\"94\">D.O.B:</td><td height=\"25\" width=\"165\"><select value=day name=\"day\" onBlur=\"datevalidate()\">\r\n");
int i=1;
while(i<=31){

      out.write("\r\n");
      out.write("<option value=");
      out.print(i);
      out.write('>');
      out.print(i);
      out.write("</option>");
i++;}
      out.write("</select>\r\n");
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<select value=month name=\"mon\" onBlur=\"datevalidate()\">\r\n");
      out.write("<option value=\"jan\">jan</option>\r\n");
      out.write("<option value=\"feb\">feb</option>\r\n");
      out.write("<option value=\"mar\">mar</option>\r\n");
      out.write("<option value=\"apr\">apr</option>\r\n");
      out.write("<option value=\"may\">may</option>\r\n");
      out.write("<option value=\"jun\">jun</option>\r\n");
      out.write("<option value=\"jul\">jul</option>\r\n");
      out.write("<option value=\"aug\">aug</option>\r\n");
      out.write("<option value=\"sep\">sep</option>\r\n");
      out.write("<option value=\"oct\">oct</option>\r\n");
      out.write("<option value=\"nov\">nov</option>\r\n");
      out.write("<option value=\"dec\">dec</option>\r\n");
      out.write("</select></td><td>\r\n");
      out.write("<select value=year name=\"year\" >\r\n");
int j=1970;
while(j<=2020){

      out.write("\r\n");
      out.write("<option value=");
      out.print(j);
      out.write('>');
      out.print(j);
      out.write("</option>");
j++;}
      out.write("</select></td></tr><tr><td height=\"10\"></td></tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr><td height=\"25\">Degree</td><td height=\"25\"><input type=\"text\" name=\"degree\" onBlur=\"len3()\"></td><td height=\"25\">subject:</td><td height=\"25\"><input type=\"text\" name=\"subject\" onBlur=\"len4()\"></td></tr><tr><td height=\"10\"></td></tr>\r\n");
      out.write("<tr><td height=\"25\">Contact no:</td><td height=\"25\"><input type=text  name=\"contactno\" onBlur=\"len10()\"></td>\r\n");
      out.write("<td height=\"25\">Email-id</td><td height=\"25\"><input type=text  name=\"emailid\" ></td></tr><tr><td height=\"10\"></td></tr>\r\n");
      out.write("<tr><td height=\"59\">&nbsp;ADDRESS:</TD><TD height=\"59\"><textarea rows=5 cols=15 name=\"address\" onBlur=\"len9()\"></textarea></td></tr><tr><td height=\"10\" ></td></tr>\r\n");
      out.write("<tr><td height=\"25\">Proffesion</td><td height=\"25\"><select name=\"prof\">\r\n");
      out.write("<option value=\"Assistant\">Assistant professor</option>\r\n");
      out.write("<option value=\"professor\">professor</option>\r\n");
      out.write("<option value=\"Nonteaching-staff\">Nonteaching-staff</option>\r\n");
      out.write("<option value=\"adminstaff\">Admin staff</option>\r\n");
      out.write("</select></td></tr><tr><td height=\"10\"></td></tr>\r\n");
      out.write("\r\n");
      out.write("<tr><td height=\"25\">Total Salary</td><td height=\"25\"><input type=text  name=\"sal\" onBlur=\"len12()\"></td><td height=\"25\">salary per day</td><td height=\"25\"><input type=text  name=\"classsal\" onBlur=\"len13()\"></td></tr>\r\n");
      out.write("<tr><td height=\"20\"></td></tr><tr><td height=\"10\"></td></tr>\r\n");
      out.write("<tr><td height=\"27\"><input type=submit name=s1 value=\"Submit\"></td>\r\n");
      out.write("<td height=\"27\"><input type=reset name=r1 value=\"Reset\"></td></tr>\r\n");
      out.write("<tr><td height=\"10\"></td></tr>\r\n");
      out.write("\r\n");
      out.write("</table></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</td></tr>\r\n");
      out.write("</table></td></tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr><td><table width=\"800\" cellpadding=0 cellspacing=0>\r\n");
      out.write(" <tr><td class=fo >\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table cellpadding=0 cellspacing=0 width=\"800\" >\r\n");
      out.write("  <tr><td width=\"48\"><IMG height=36 src=\"img/m33.gif\" width=42 align=left ></td>\r\n");
      out.write("    <td class=fo width=\"800\">All Rights Reserved. </td>\r\n");
      out.write("    <td align=right width=\"220\" class=fo><IMG height=36 src=\"img/m35.gif\" width=214 ></td></tr>\r\n");
      out.write(" </table></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</BODY>\r\n");
      out.write("</HTML>\r\n");
}catch(Exception e)
{}

      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
