/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.26
 * Generated at: 2016-04-12 06:26:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.Dbconnection.Dbconnection;

public final class timer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

Connection con=null;
    PreparedStatement stmt,stmt1,ac;
	ResultSet rs,rs1,r;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
try
{
     int z;
	 out.println("hi");
	 String vv=request.getParameter("v");
	 if(vv.equals("1"))
	{
		response.sendRedirect("exam.jsp?v=1");
	}
	 String uid=(String)session.getAttribute("uid1");
	 out.println(uid);
	 con=Dbconnection.getConnection();
ac=con.prepareStatement("select count(*) from exampaper");
r=ac.executeQuery();
r.next();
int p=r.getInt(1);
if(p==0)
	{
	response.sendRedirect("exam3.jsp?v=1");
	}
    stmt=con.prepareStatement("select sysdate()+0");
    rs=stmt.executeQuery();
    rs.next();
	stmt1=con.prepareStatement("select activ,gap from exampaper");
    rs1=stmt1.executeQuery();
    rs1.next();

	String time=rs.getString(1);
	

	 int i=Integer.parseInt(time.substring(0,2));
	 int j=Integer.parseInt(time.substring(3,5));
   String time1=rs1.getString(1);
  
     int x=Integer.parseInt(time1.substring(0,2));
	 int y=Integer.parseInt(time1.substring(3,5)); 
	
	 
	String dur=rs1.getString(2);
    int l=x;    
	int k=y+Integer.parseInt(dur);
	if(k>=60)
	{
		k=k-60;
		if(l==12)
		{
			l=1;
		}
		else
		{
        l=l+1;
		}
	}
		



      out.write("\r\n");
      out.write("\r\n");
session.setAttribute("uid1",uid);
      out.write("\r\n");
      out.write("<HTML>\r\n");
      out.write("<meta http-equiv=\"refresh\" content=\"60\"><body>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write(" <BODY>\r\n");
      out.write("\r\n");

      
      if(i==x ||i==l)
	  {
	     if(i==x)
		 {
  			if(y<=j)
			 {
				 
				response.sendRedirect("exam.jsp?v=0");
				
			 }
			  else
	        {
      out.write("\r\n");
      out.write("\t        <center>Exam is activated At ");
      out.print(time1);
      out.write("<br>Current time:");
      out.print(time);
      out.write("</center>\r\n");
      out.write("             ");
}

		 }
		 else
			 {
				 if(k>=j)
				 {
					response.sendRedirect("exam.jsp?v=0");
					
				 }
				  else
	              {
	             
      out.write("\r\n");
      out.write("\t\t  <center>Presently no exam is activated</center> \r\n");
      out.write("\t");
 }	
			 }
	  }
	  else if(i>x || i>l)
	  {
		  
      out.write("\r\n");
      out.write("\t\t  <center>Presently no exam is activated</center> \r\n");
      out.write("\t");
 }
	  else
	 {
      out.write("\r\n");
      out.write("\t <center>Exam is activated At ");
      out.print(time1);
      out.write("<br>Current time:");
      out.print(time);
      out.write("</center>\r\n");
      out.write("     ");
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" </BODY>\r\n");
      out.write("</HTML>\r\n");
}catch(Exception e)
{out.println(e);}

      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
